### ISSUE TITLE
Ubuntu 22.04 not compatible with CNCLI due to OpenSSL upgrade?

### ISSUE THREAD

**Issue by Cryptowolverine** [AndrewWestberg/cncli#109]
Hi Andrew - I've recently upgraded to Ubuntu 22.04 and it appears it uses OpenSSL 3.0.  I believe CNCLI integrates the prior version (1.1.1), so I'm getting the following error when running CNCLI on Ubuntu 22.04.  Not sure if I'm understanding the issue correctly?
cncli: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by AndrewWestberg** [comment]
@Cryptowolverine Have you tried re-compiling cncli yourself instead of downloading the binaries? I'm running on 22.04 on a new machine where I built it myself and it seems to be ok.

**Comment by Cryptowolverine** [comment]
Thanks Andrew, let me have a go at that.  I installed using Guild Operators prereqs.
