### ISSUE TITLE
Problem with SSL certificate

### ISSUE THREAD

**Issue by diegueins680** [AndrewWestberg/cncli#15]
After running 

cargo install --path . --force --debug

I get the following output:

  Installing cncli v0.5.4 (/home/frodo/git/cncli)
    Updating crates.io index
    Updating git repository `https://github.com/AndrewWestberg/rust-cardano-ouroboros-network`
   Compiling cncli v0.5.4 (/home/frodo/git/cncli)
error: failed to compile `cncli v0.5.4 (/home/frodo/git/cncli)`, intermediate artifacts can be found at `/home/frodo/git/cncli/target`

Caused by:
  failed to run custom build command for `cncli v0.5.4 (/home/frodo/git/cncli)`

Caused by:
  process didn't exit successfully: `/home/frodo/git/cncli/target/debug/build/cncli-5c885c45af504984/build-script-build` (exit code: 101)
  --- stdout
  cncli/build.rs:44: Executing "git" "submodule" "update" "--init" "--recursive"
  cncli/build.rs:48: Command "git" "submodule" "update" "--init" "--recursive" finished successfully
  cncli/build.rs:44: Executing "git" "checkout" "66f017f1"
  cncli/build.rs:48: Command "git" "checkout" "66f017f1" finished successfully
  cncli/build.rs:44: Executing "git" "reset" "--hard" "HEAD"
  HEAD is now at 66f017f1 Fix issue when building VRF tests with g++
  cncli/build.rs:48: Command "git" "reset" "--hard" "HEAD" finished successfully
  cncli/build.rs:44: Executing "./autogen.sh"
  Downloading config.guess and config.sub...
  Done.
  cncli/build.rs:48: Command "./autogen.sh" finished successfully
  cncli/build.rs:44: Executing "./configure"

  --- stderr
  HEAD is now at 66f017f1 Fix issue when building VRF tests with g++
  autoreconf: Entering directory `.'
  autoreconf: configure.ac: not using Gettext
  autoreconf: running: aclocal --force -I m4
  autoreconf: configure.ac: tracing
  autoreconf: configure.ac: not using Libtool
  autoreconf: running: /nix/store/8qkzlc2rd6gz535jkw0lh9qiqprm2cy9-autoconf-2.69/bin/autoconf --force
  configure.ac:855: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
        If this token and others are legitimate, please use m4_pattern_allow.
        See the Autoconf documentation.
  autoreconf: /nix/store/8qkzlc2rd6gz535jkw0lh9qiqprm2cy9-autoconf-2.69/bin/autoconf failed with exit status: 1
  curl: (60) SSL certificate problem: unable to get local issuer certificate
  More details here: https://curl.se/docs/sslcerts.html

  curl failed to verify the legitimacy of the server and therefore could not
  establish a secure connection to it. To learn more about this situation and
  how to fix it, please visit the web page mentioned above.
  curl: (60) SSL certificate problem: unable to get local issuer certificate
  More details here: https://curl.se/docs/sslcerts.html

  curl failed to verify the legitimacy of the server and therefore could not
  establish a secure connection to it. To learn more about this situation and
  how to fix it, please visit the web page mentioned above.
  configure: error: cannot find install-sh, install.sh, or shtool in build-aux "."/build-aux
  thread 'main' panicked at 'failed to execute "./configure"', build.rs:46:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by AndrewWestberg** [comment]
You likely have a local issue preventing your server from downloading something with curl when compiling libsodium.

cd into the libsodium folder and manually run some of the commands in build.rs like...
```
$ ./autogen.sh
$ ./configure
```
This will give us more information about what is going wrong on your particular server.
