### ISSUE TITLE
Leaderlogs NEEDS to match cardano-node math EXACTLY

### ISSUE THREAD

**Issue by AndrewWestberg** [AndrewWestberg/cncli#20]
There are still a few areas like the natural log (ln) function that don't match the output of the haskell counterpart exactly. At very small levels of stake, this can result in giving a different leaderlog answer than the node for small pools. Figure out how we can make it match exactly and open up issues on the IOG side if need be.

**Comment by amani1104** [comment]
Is believe this issue is also present for mid-size pools. During epoch 243, cncli already indicated two blocks for my pool that where not minted, not involved in slot battles and where I don't find issues in my monitoring.

**Comment by AndrewWestberg** [comment]
@amani1104 Thanks for this report. I'm actively working on getting this to match up more exactly.

**Comment by amani1104** [comment]
It turned out now that the two blocks were correctly identified by cncli. It seems to have been a database issue on the end of both pooltool and adapools, as both blocks have now showed up there.

**Comment by AndrewWestberg** [comment]
Fixed in v1.0.0
