### ISSUE TITLE
cross-compile to x86_64-unknown-linux-musl fails because of gmp-mpfr-sys dependency

### ISSUE THREAD

**Issue by panssystem** [AndrewWestberg/cncli#21]
I'm using the clux/muslrust docker package to cross-compile to x86_64-unknown-linux-musl for use in Azure. 

I'm not an expert on Rust, but I've solved this in my personal environment by adding
`
gmp-mpfr-sys = { features=["force-cross"] }
`
to dependencies for this project. I think another option would be to support the force-cross feature in the project itself?

Anyway, I'd appreciate some advice on the best way to handle this. This fix seems to work, but I'm not sure it's "correct."

**Comment by AndrewWestberg** [comment]
I'm not an expert on rust either. This is my first ever rust project. As long as there doesn't seem to be any large negative side effects to adding this build flag, go ahead and send me a pull request for the update.

**Comment by panssystem** [comment]
Added the PR.

**Comment by AndrewWestberg** [comment]
resolved
