### ISSUE TITLE
symbol lookup error:

### ISSUE THREAD

**Issue by TrevorBenson** [AndrewWestberg/cncli#3]
**Description:**
Compiling cncli v0.2.3 from documentation produced no errors, all download/compiling/installing steps appear to be successful, however the following error is thrown when checking cncli version:

```
$ cncli -V
cncli: symbol lookup error: cncli: undefined symbol: crypto_vrf_prove
```
**Expectation:**
Compiling to succeed and cncli to not return errors on version check & other flags/subcommands.

**Version:**
 - OS: Fedora 33
 - Product version: cncli v0.2.3

**Comment by TrevorBenson** [comment]
From reading the [Shelley SPO BP Workgroup](https://t.me/CardanoStakePoolWorkgroup) it appears this is related to system libsodium instead of the IOHK patched libsodium. 

I'll give that a try this evening and close the issue out if successful.

**Comment by AndrewWestberg** [comment]
This must point at the iohk version of libsodium.
