### ISSUE TITLE
Add CI for Windows

### ISSUE THREAD

**Issue by AndrewWestberg** [AndrewWestberg/cncli#34]
Build CI pipeline for Windows machines.

**Comment by michaeljfazio** [comment]
Coming to a cncli near you soon....

![image](https://user-images.githubusercontent.com/1845178/108631911-4a4f3f00-74a7-11eb-8546-87f8e7a7feb4.png)

**Comment by AndrewWestberg** [comment]
Noice!

**Comment by AndrewWestberg** [comment]
merged
