### ISSUE TITLE
[Feature]Block Number Getter Function

### ISSUE THREAD

**Issue by NoCtrlZ** [AndrewWestberg/cncli#4]
@AndrewWestberg 
Hi, my name is Shin.
I think this is a really cool project.
Do you have any plan to support getting block numbers from Cardano's full node?

**Comment by AndrewWestberg** [comment]
@NoCtrlZ You should be able to get this from the sync'd database itself without waiting for me.

```
sqlite3 cncli.db "select * from chain where block_number=######"
```

**Comment by NoCtrlZ** [comment]
Thank you!
