### ISSUE TITLE
leaderlog fails from blank file using API instead of --ledger-state

### ISSUE THREAD

**Issue by rphair** [AndrewWestberg/cncli#43]
As of this epoch (251) we get this error when running `cncli leaderlog` with a fully synced database (reports `"status": "ok"` from `cncli status` immediately before it in command sequence) and this syntax:

`cncli leaderlog --db ./db/cncli.db --pool-id c94e6fe1123bf111b77b57994bcd836af8ba2b3aa72cfcefbec2d3d4 --pool-vrf-skey ./config/vrf.skey --byron-genesis ./config/mainnet-byron-genesis.json --shelley-genesis ./config/mainnet-shelley-genesis.json --ledger-set current --tz Asia/Kolkata`

`{
  "status": "error",
  "errorMessage": "EOF while parsing a value at line 1 column 0"
}`

I guessed that it might have been failing on getting the sigma from the API `https://api.crypto2099.io/v1/sigma` by default since that URI returns a blank file upon error.  Maybe that script isn't updated to work after the Mary hard fork: but I don't know that API syntax so I can't test if that's the problem.

Anyway I've titled this as an API issue because it works properly when generating & passing `--ledger-state`:

`cncli leaderlog --db ./db/cncli.db --pool-id c94e6fe1123bf111b77b57994bcd836af8ba2b3aa72cfcefbec2d3d4 --pool-vrf-skey ./config/vrf.skey --byron-genesis ./config/mainnet-byron-genesis.json --shelley-genesis ./config/mainnet-shelley-genesis.json --ledger-set current --ledger-state ledger.251.json --tz Asia/Kolkata`

Please also @AndrewWestberg post here the correct syntax for that crypto2099 API link so we can test when our usual mechanism might be fixed.

**Comment by Crypto2099** [comment]
Yeah, the db-sync instance that the API was connected to decided to crash out during the HFC event. It's been investigated and should now be repaired and working properly once again and have more disaster recovery redundancy should this situation arise in the future.

**Comment by rphair** [comment]
thanks @Crypto2099 ... what's the correct syntax for API links beginning `https://api.crypto2099.io/v1/sigma`?  Is there a page or something that lists those API endpoints and how they work?

**Comment by Crypto2099** [comment]
Hey,

We're still working on documentation and fully fleshing it out, current endpoints that exist should be:
https://api.crypto2099.io/v1/sigma/[pool_id (bech32|hex)]/[epoch_no (default next epoch)]
https://api.crypto2099.io/v1/epoch/[epoch_no (default next epoch)]

I will probably look at making the default page (https://api.crypto2099.io) a guide to utilizing the API.

**Comment by AndrewWestberg** [comment]
Closing this out for now since it looks like all the relevant info on the api has been shared.

**Comment by monkey-jsun** [comment]
sorry, what is the fix?  I just had this issue right now.

cncli leaderlog --byron-genesis testnet-byron-genesis.json --pool-id $(cat stake-pool-id.txt) --pool-vrf-skey vrf.skey --shelley-genesis testnet-shelley-genesis.json --db ../cncli/cncli.db 
{
  "status": "error",
  "errorMessage": "EOF while parsing a value at line 1 column 0"
}

**Comment by AndrewWestberg** [comment]
Try using absolute paths to cncli.db.

**Comment by monkey-jsun** [comment]
I solved the problem export ledger state first and then pass it as an additional argument.  And it worked.  If this argument is necessary, maybe it should be made mandatory?  Or if the ledger file is missing, there should be more obvious error message? I'm not an expert here.  I'm just using it for the first time.

**Comment by rphair** [comment]
@Crypto2099 I don't know an official means of reporting this (can you post that here?) but the `/sigma` endpoint is down at this time, hence the same problem.  e.g. this link generates a zero sized file:
`https://api.crypto2099.io/v1/sigma/c94e6fe1123bf111b77b57994bcd836af8ba2b3aa72cfcefbec2d3d4`

**Comment by AndrewWestberg** [comment]
@rphair The API should be back up. It's taking longer and longer each epoch to generate the ledger dump on the API side. In the next version of the node, Kevin Hammond from IOG has given us a new command that should make dumping ledger state for cncli a thing of the past. We won't need the api any longer either.

**Comment by rphair** [comment]
@AndrewWestberg hope that coming integration with the node will work for the epoch nonce API as well... still don't know official means of reporting API failure, other than here... right now both the `/epoch` and `/sigma` endpoints are timing out.

**Comment by AndrewWestberg** [comment]
@rphair It should work for both nonce and leaderlogs. If you want to test it early, you can build the `stake-snapshot` branch and install the latest cardano-node from the master branch. It shouldn't hurt anything as long as it's a private relay you're testing against.  Usage looks something like this: https://paste.ubuntu.com/p/x5pJmMDywY/

**Comment by AndrewWestberg** [comment]
Use `poolStakeMark` and `activeStakeMark` if you're going to run leaderlogs for `next`.

**Comment by rphair** [comment]
@Crypto2099 - for environments where we can't make these software changes yet, is the API going to be coming back online before the next epoch begins? According to Cloudflare it's a host error, and from my observation the usual API endpoints have been down for at least the last 3½ hours.
