### ISSUE TITLE
Leaderlog fails with 'invalid type' error message

### ISSUE THREAD

**Issue by riyavsinha** [AndrewWestberg/cncli#44]
```
$ cncli leaderlog --db /opt/cardano/cnode/guild-db/cncli/cncli.db --byron-genesis /opt/cardano/cnode/files/byron-genesis.json --shelley-genesis /opt/cardano/cnode/files/genesis.json --ledger-set current  --pool-id 420d1ed89bb8bf46f867936b8c2a7b9b3e759d161e46d561cc6bd985 --pool-vrf-skey /opt/cardano/cnode/priv/pool/shakti/vrf.skey --tz UTC
{
  "status": "error",
  "errorMessage": "invalid type: null, expected u64 at line 1 column 74"
}
```

My node is running, and sync says 100% synced. I understand this may be a user error not falling within the bounds of a GitHub issue, but some sort of catch statement on failures to add additional error context would be really helpful-- I have absolutely no idea what may be my issue, and neither does anyone else I ask it seems :-/ 

I have checked all the files referenced and they seem to be proper

**Comment by riyavsinha** [comment]
Please confirm:

In leaderlog.rs, the only `u64` defined type is in the `LeaderLog` struct:

```
struct LeaderLog {
    status: String,
    epoch: i64,
    epoch_nonce: String,
    epoch_slots: i64,
    epoch_slots_ideal: f64,
    max_performance: f64,
    pool_id: String,
    sigma: f64,
    active_stake: u64,
    total_active_stake: u64,
    d: f64,
    f: f64,
    assigned_slots: Vec<Slot>,
}
```

If my pool is relatively new and therefore has no active stake at the moment, could that be the parsing error?

**Comment by AndrewWestberg** [comment]
If you have no active stake, I believe that can cause this error.
