### ISSUE TITLE
Error: A query from a certain era was applied to a ledger from a different era: EraMismatch {ledgerEraName = "Mary", otherEraName = "Allegra"}

### ISSUE THREAD

**Issue by ianoble** [AndrewWestberg/cncli#46]
When trying to get the ledger state json, from the README file:

> 1.) use cardano-cli to dump a fresh ledger-state.json file. This is optional if you're using the API instead of a ledger-state json file.
> 
> $ cardano-cli query ledger-state --allegra-era --mainnet > /tmp/ledger-state-227.json

**Comment by AndrewWestberg** [comment]
Updated the docs for the Mary era 

`--allegra-era` -> `--mary-era`
