### ISSUE TITLE
Can a pool config be wrong in such a way that leaderlog shows nothing?

### ISSUE THREAD

**Issue by tdiesler** [AndrewWestberg/cncli#48]
Over the last few epochs, I've seen some weird behavior. First, the [pool](https://adapools.org/pool/9e8009b249142d80144dfb681984e08d96d51c2085e8bb6d9d1831d2) minted 4 blocks in epoch 250 and I saw for a brief moment a delegator with 1.4m, which would explain that. This however does not show up in cardano-db-sync epoch_stake - how can that be?

Then, leaderlog shows no assigned slots for 251, 252, 253

```
$ cncli leaderlog \
>   --pool-id 9e8009b249142d80144dfb681984e08d96d51c2085e8bb6d9d1831d2 \
>   --shelley-genesis /opt/cardano/config/mainnet-shelley-genesis.json \
>   --byron-genesis /opt/cardano/config/mainnet-byron-genesis.json \
>   --pool-vrf-skey /var/cardano/keys/pool/vrf.skey \
>   --db /var/cardano/cncli/cncli.db \
>   --tz Europe/Berlin \
>   --ledger-set current
{
  "status": "ok",
  "epoch": 253,
  "epochNonce": "f4c7a51392799ee9da58c5ecebc81e25fe001ba93869ba5700c5d7a5558c2a5a",
  "epochSlots": 0,
  "epochSlotsIdeal": 0.77,
  "maxPerformance": 0.0,
  "poolId": "9e8009b249142d80144dfb681984e08d96d51c2085e8bb6d9d1831d2",
  "sigma": 0.000038499997392550907,
  "activeStake": 878091332721,
  "totalActiveStake": 22807568628326603,
  "d": 0.08,
  "f": 0.05,
  "assignedSlots": []
}
```

There is less than 1% probability that this is simply bad luck and I'm now wondering whether it is at all possible that something is wrong with the pool config. I switched from CLI based keys to HW keys for reward and owner.

What parameters from the pool does leaderlog actually use apart from activeStake? Would it detect an invalid vrf.skey? In general, is there any way I can verify that this is really "just bad luck"?
Up until now leaderlog is consistent with pool runtime behavior, which makes me believe that if something was wrong it must effect leaderlog too.

Would it theoretically possible to run the leaderlog for a whole month or even year (on the assumption that active/total stake stay constant)? This would of course not give reliable results, but may still have some merit if only to give a rough idea what a schedule could look like.

Cheers

**Comment by AndrewWestberg** [comment]
This isn't really bad luck. There is only 878k in active stake. It's perfectly reasonable to get assigned no blocks in an epoch given that level of stake. There is a 53% chance you get zero blocks.

![Screenshot from 2021-03-12 16-52-06](https://user-images.githubusercontent.com/245918/110971913-59613880-8353-11eb-83c3-9964e83ea8b2.png)
