### ISSUE TITLE
Bad error message for pools that don't have active stake yet

### ISSUE THREAD

**Issue by FoodPoolCardano** [AndrewWestberg/cncli#49]
cncli leaderlog returning for pools that do not have any active stake yet. Which is very typical in the first two epochs of a new block:

Error message: invalid type: null, expected u64 at line 1 column 74

**Comment by AndrewWestberg** [comment]
Valid bug... will fix in an upcoming release.

**Comment by AndrewWestberg** [comment]
Fixed in 1.4.1
