### ISSUE TITLE
Added support for historical epochs

### ISSUE THREAD

**Issue by tdiesler** [AndrewWestberg/cncli#55]
Checking the leader schedule for epochs in the past may be useful for forensic reasons when folks are wondering whether their pool might have been scheduled for a block, but didn't mint one. Related to this [forum post](https://forum.cardano.org/t/slightly-disappointed-as-of-late/55596/3).

**Comment by AndrewWestberg** [comment]
This should be doable as long as we use the API to gather historical sigma, d, and nonce values. It's unlikely we can make it work from really old ledger state dumps as they would not be compatible.

**Comment by tdiesler** [comment]
Great, thanks.

**Comment by AndrewWestberg** [comment]
Closing as won't do because its not possible to get old sigma and d values accurately.
