### ISSUE TITLE
missing field `esPrevPp`

### ISSUE THREAD

**Issue by mark-microtick** [AndrewWestberg/cncli#58]
Getting a new error after upgrading to cardano-node v1.26.1 this morning.  They seem to have removed a field somewhere?

**Comment by AndrewWestberg** [comment]
Make sure to take a fresh ledger dump. The field should be in there.

**Comment by AndrewWestberg** [comment]
Also check to make sure your ledger dump command is actually working. You need to remove the `--mary-era` from the command.

**Comment by mark-microtick** [comment]
Hmm.  I just took a fresh snapshot and the field is in there, but only in the "stateBefore" JSON object:

{
    "stateBefore": {
        "esPrevPp": {
            ...
            
I just verified that I still see the bug using --ledger-set current in the current epoch

**Comment by mark-microtick** [comment]
Also, yes, I did remove the --mary-era because that was giving an error.

**Comment by AndrewWestberg** [comment]
What version of cncli?

**Comment by mark-microtick** [comment]
Actually, good question.  I'm not sure because the -V flag returns a different version than the git version I checked out and built:

$ git status
HEAD detached at v1.5.1

$ ./target/release/cncli -V
cncli 1.0.1

**Comment by mark-microtick** [comment]
... and that pointed out the issue.  Sorry, was running an older release binary but building the debug binary...   will close this
