### ISSUE TITLE
Windows Builds under MSYS/2 Failing

### ISSUE THREAD

**Issue by michaeljfazio** [AndrewWestberg/cncli#61]
Seems that the reason windows builds have been failing is because the MSYS2 environment has changed underneath us. Previously, the PKG_CONFIG_PATH was being set automatically to /mingw64/lib/pkgconfig which is where the libsodium.pc was being [installed](https://github.com/AndrewWestberg/cncli/runs/2239254527?check_suite_focus=true#step:6:2449). In newer builds the libsodium.pc is being [added to /lib/pkgconfig instead](https://github.com/AndrewWestberg/cncli/runs/2298213765?check_suite_focus=true#step:6:2449), and it would seem that PKG_CONFIG_PATH is not being setup automatically.

**Comment by AndrewWestberg** [comment]
closing as won't do. will be turning off the windows build.
