### ISSUE TITLE
Issue running leaderlog on cncli 2.0.0

### ISSUE THREAD

**Issue by pascallapointe** [AndrewWestberg/cncli#62]
Cncli is reporting the following error message while attempting to use `cncli leaderlog` in version 2.0.0:

```
{
    "status": "error",
    "errorMessage": "expected value at line 1 column 1"
}
```

The command launch was the following:

`cncli leaderlog --byron-genesis byron-genesis.json --shelley-genesis shelley-genesis.json --ledger-state ledger.json --pool-id 2a748e3885f6f73320ad16a8331247b81fe01b8d39f57eec9caa5091 --pool-vrf-skey vrf.skey --db ../guild-db/cncli/cncli.db --tz America/Montreal --ledger-set next`

Will revert to version 1.5 to see if the issue resolve.

**Comment by wutzebaer** [comment]
hi i have the same problem, even if i revert to 1.4.1 which worked this morning, i think it's the new cardano-node version which i istalled just beforee

**Comment by AndrewWestberg** [comment]
Try using an absolute path to ledger-state.json

**Comment by pascallapointe** [comment]
The cardano-cli ledger-state doesn't dump the file in json format anymore since cardano-node version 1.26.1.

Looks like it is the issue

**Comment by wutzebaer** [comment]
i did not resolve the issue but,

`cardano-cli query ledger-state --mary-era --mainnet` i had to remove the "--mary-era" parameter from my command when creating the ledgerstate. The paramter is deprecated and leads to an error message as output. 

after that version 1.5.1 still gives me an error

```
{
  "status": "error",
  "errorMessage": "Query returned no rows"
}
```

**Comment by wutzebaer** [comment]
Oh my bad i tred to run next, but next is currently not available, since the next epoch starts in more than 1.5 days. So i can say the problem is solved for me now.

**Comment by wutzebaer** [comment]
2.0.2 is also working now

**Comment by the-headless-ghost** [comment]
For me, version 2.0.2 and with the newest developer commit did not resolve this issue. @AndrewWestberg I also tried with tried with absolute paths.

**Comment by the-headless-ghost** [comment]
Ok, I think I found out what's the issue. When creating the ledger state you can either pipe the `stdout` to a file or using the `--out-file` parameter. When using the parameter the output file looks like a binary file, that's when I got the cncli error, but when using the pipe you get a text file.
