### ISSUE TITLE
leaderlog returns error for "next" epoch, "Query returned no rows"

### ISSUE THREAD

**Issue by monkey-jsun** [AndrewWestberg/cncli#67]
When I tried to query for next epoch, it seems it always returns the above error.  Was there some restrictions here for query next epoch?

checking leaders .... this may take a long time
{
  "status": "error",
  "errorMessage": "Query returned no rows"
}

**Comment by AndrewWestberg** [comment]
![Screenshot from 2021-04-21 18-32-44](https://user-images.githubusercontent.com/245918/115603727-06728d80-a2d0-11eb-94a4-0a5ee6cd7b74.png)
