### ISSUE TITLE
Calculate return on ADA percentage

### ISSUE THREAD

**Issue by rynz** [AndrewWestberg/cncli#68]
```
Leaderslots: 2 - Ideal slots for epoch based on active stake: 2.27 - Luck factor 88.11%
```

How does one calculate return on ADA percentage? Eg ADAPools specifies ROA in the rewards tab.

Is this something that can be calculated manually or added to leaderlog?

**Comment by AndrewWestberg** [comment]
It could be estimated, but it really doesn't belong in leaderlogs. Adapools and pooltool calculate it differently.

**Comment by rynz** [comment]
@AndrewWestberg how do they calculate it, do you know? I know quite a few Delegators would like this kind of feature, even if just an estimate.

**Comment by AndrewWestberg** [comment]
I'd have to talk with them. I think pooltool assumes compound interest and adapools does not... Or I have that backward. I still don't think It should be giving estimated ROA values. I prefer to stick with % luck based on ideal number of blocks. Maybe it's just me, but it's a don't like to count chickens before they hatch type of thing.

**Comment by AndrewWestberg** [comment]
It also gets into needing a ton more info than I currently require to do leaderlogs. ROA requires knowledge about a pool's fees, margin, etc... leaderlogs just simply doesn't care about any of those values.

**Comment by rynz** [comment]
What's your opinion on adding a `roa` command? Perhaps it's something everyone could adopt with cncli to become the defacto standard.

**Comment by AndrewWestberg** [comment]
Just look at it on pooltool. There's no reason for cncli to reinvent the wheel.
