### ISSUE TITLE
leaderlog: fails on empty file somewhere (maybe from API)

### ISSUE THREAD

**Issue by rphair** [AndrewWestberg/cncli#69]
I know this message gets reported frequently but I can't get through the usual ways of working around it.  From `cncli leaderlog`:
```
{
  "status": "error",
  "errorMessage": "expected value at line 1 column 1"
}
```

At this moment the `/epoch` API is generating a readable file & nonce for the following epoch: https://api.crypto2099.io/v1/epoch/

... but the pool sigma API generates an empty file (e.g. for our pool): https://api.crypto2099.io/v1/sigma/c94e6fe1123bf111b77b57994bcd836af8ba2b3aa72cfcefbec2d3d4

However it doesn't seem the latter is the problem since `leaderlog` also fails when passed the ledger state, as per the common workaround:

`cncli leaderlog --db /home/.../cncli.db --pool-id c94e6fe1123bf111b77b57994bcd836af8ba2b3aa72cfcefbec2d3d4 --pool-vrf-skey /home/.../.../vrf.skey --byron-genesis /home/.../.../mainnet-byron-genesis.json --shelley-genesis /home/.../.../mainnet-shelley-genesis.json --tz Asia/Kolkata --ledger-set next --ledger-state /home/.../tmp/ledger-state`

Also if were sure that the `/sigma` API endpoint *was* causing this problem I also wouldn't know how to report that issue (asked @Crypto2099 in https://github.com/AndrewWestberg/cncli/issues/43#issuecomment-829184052 but this issue is closed).

*cncli 2.0.3 - Ubuntu 20.04*

**Comment by AndrewWestberg** [comment]
I'm seeing the api is no longer generating an empty file.

**Comment by rphair** [comment]
thanks for second response & I've confirmed this as well based on https://github.com/AndrewWestberg/cncli/issues/43#issuecomment-829358766.  The last time the script was running as usual through the API.
