### ISSUE TITLE
Allow defining script inputs in an env file

### ISSUE THREAD

**Issue by AndrewWestberg** [AndrewWestberg/cncli#7]
It would be nice to not have to put in all of the commandline parameters each time. We should have the option of reading them from an env file in the current folder.

**Comment by lordb-rocks** [comment]
I created aliases for all of the commands that pass in the options I want.
`alias cnstatus='cncli status --byron-genesis $NODE_HOME/mainnet-byron-genesis.json --shelley-genesis $NODE_HOME/mainnet-shelley-genesis.json --db $NODE_HOME/cncli/cncli.db'`
