### ISSUE TITLE
feature request - calculate network delay based on actual slot number

### ISSUE THREAD

**Issue by laplasz** [AndrewWestberg/cncli#72]
Hi There!

It is possible to calculate the network delay (or propagation time) based on the current tip.
currently the log files contains such statement when there is a new tip:

`[dell:cardano.node.ChainDB:Notice:265] [2021-03-25 21:04:33.57 UTC] Chain extended, new tip: 720267abd1f74bfcc9eb6a107ffe09c95188e371d6b6fd17907771e47c66d5bc at slot 25139982`

I have created a topic on cardano forum about the details how to get the delay:
https://forum.cardano.org/t/network-delay-calculation-based-on-logs/55948?u=laplasz

So this delay time could be inserted in to BLOCKLOG_DB as a new column for a block row.

or logMonitor.sh could update the block with this info
What do you think? Thanks!

**Comment by AndrewWestberg** [comment]
What would be the usecase for calculating the delay? We're already sending our tips to pooltool and they are calculating the delay for us. I guess slightly more accuracy since we wouldn't have the latency between us and pooltool included in the propagation?

**Comment by laplasz** [comment]
Hi!

Thanks for the answer - yes, the usecase would be to get this stat offline.. since the info is available in the logs, so no need to use pooltool - and yes, offline calculation would provide more accurate values..

**Comment by papacarp** [comment]
pooltool uses the timestamp you report along with the calculated slot time.  So there is no impact from latency. Due to our needs to have our nodes pretty well time synchronized I felt it was better to allow the reporter to timestamp the block and send that data to pooltool rather than have pooltool timestamp it (and introduce unknown latency variations).
