### ISSUE TITLE
New Token Metadata Not passing CI Checks from CF

### ISSUE THREAD

**Issue by MrMitch17** [AndrewWestberg/cncli#73]
Hello,

I submitted the metadata.json file when creating a new native token to CF for merger into the token registry.  The first Token I submitted about a week ago, they accepted, however, one that just went through was not accepted due to the tool field failing CI checks.

You can see the details here
https://github.com/cardano-foundation/cardano-token-registry/pull/108

I just wanted to give you a heads up.

Thanks for all you do!

**Comment by AndrewWestberg** [comment]
This project doesn't have anything to do with the token registry. Please open an issue on that project instead.
