### ISSUE TITLE
Correct output for pool with no current leader slots...?

### ISSUE THREAD

**Issue by stackBlock** [AndrewWestberg/cncli#76]
Hey, 

Thanks for all the tools you built for the Cardano Stake pools. I have a quick question, If you search for the slot leader schedule, do you get 'null' as the output if youi do not have any slots for the epoch? 

This is my output:
`MYPOOL - null `🎰`,  null% `🍀max, `null` 🧱ideal

Is this correct, or is there an error in the processing? 

Thanks,
Anthony

**Comment by AndrewWestberg** [comment]
The script could probably be tweaked in case there are no leader slots. The
printout at the end is probably assuming there are available slots.

**Comment by stackBlock** [comment]
Thanks... sorry for not closing this issue. I have another issue that I will start a new thread for.
