### ISSUE TITLE
Add support for leaderlog on arm64

### ISSUE THREAD

**Issue by tdiesler** [AndrewWestberg/cncli#83]
I'd like to integrate cncli with the Nix build for nessusio/cardano-tools. For this it'd be good to have a generic Nix based build that works on all target platforms i.e. x86_84, x86_84-darwin, arm64

**Comment by AndrewWestberg** [comment]
Check with @disassembler . I believe he builds cncli on nix. Not sure if he does arm though.

**Comment by tdiesler** [comment]
Currently, I see ...

```
  Downloaded 162 crates (17.6 MB) in 6.42s (largest was `gmp-mpfr-sys` at 5.4 MB)
   Compiling autocfg v1.0.1
   Compiling proc-macro2 v1.0.27
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.73
   Compiling libc v0.2.97
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-Wl,--as-needed" "-L" "/home/pi/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib"
...
-unknown-linux-gnu/lib/libcore-d7926f131590f689.rlib" "-Wl,--end-group" "/home/pi/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcompiler_builtins-8e0dea81c2814a1a.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: impure path `/home/pi/git/nessus-cardano/nix/cncli/target/cncli/target/release/build/syn-8064e11de6573109/build_script_build-8064e11de6573109' used in link
          collect2: error: ld returned 1 exit status
error: aborting due to previous error
error: could not compile `syn`
To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit status: 1
```

It fails with similar errors on all three target platforms. This is likely because of some dependency issue that I couldn't translate from the documented deps to Nix packages

**Comment by tdiesler** [comment]
CrossRef: https://discord.com/channels/826816523368005654/841667492384473118/857516537174163463

**Comment by tdiesler** [comment]
I migrated the build to Nix Flakes, and now see ...

![image](https://user-images.githubusercontent.com/244946/123386928-78e53f80-d597-11eb-80fc-1b085ebc5c63.png)

This is bizarre, because apparently there is plenty of free disk space. Any idea?

**Comment by tdiesler** [comment]
This may be caused by https://github.com/NixOS/nixops/issues/1402

**Comment by tdiesler** [comment]
I also had to increase the number of inodes like this

```
sudo mount -o remount,nr_inodes=1M  /run/user/1000
```

**Comment by tdiesler** [comment]
Done
