### ISSUE TITLE
Integrate aarch64 binaries into the release process

### ISSUE THREAD

**Issue by tdiesler** [AndrewWestberg/cncli#86]
The code to produce these aarch64 binaries (#83) is available. How are we going to integrate this into the release process? 

GitHub Actions, I suppose?

**Comment by AndrewWestberg** [comment]
Probably. @michaeljfazio did the other platforms for me.

**Comment by tdiesler** [comment]
Is this closed as "won't fix" or should these binaries be available somewhere? They are not attached to the release AFAICS.
