### ISSUE TITLE
Problem running on ubuntu 18.04

### ISSUE THREAD

**Issue by stackBlock** [AndrewWestberg/cncli#87]
I am getting this error when i try to run this on my 18.04 version of ubuntu:

/usr/local/bin/cncli: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/cncli)
/usr/local/bin/cncli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/bin/cncli)

Ubuntu 18 only runs libc 2.27; 2.28 isn't available to install until version 19 or 20 natively.  It turns out trying to put anything above 2.27 on ubuntu 18.04 has been giving people issues and breaking some machines... Is there anything you can do on your end? I spent about 30 minutes trying to find good solutions but can't seem to find any.

Or if you know of a safe way to update to glibc 2.28. that would work also. 
Thanks,
Anthony

**Comment by AndrewWestberg** [comment]
Are you building it yourself or using the pre-built binaries? If the latter, try building directly on 18.04.

**Comment by stackBlock** [comment]
I will give that a try and let you know. Thanks!

**Comment by tradingalgobots** [comment]
I had same issue. following this steps to install manually fixed the problem

https://github.com/AndrewWestberg/cncli/blob/develop/INSTALL.md
