### ISSUE TITLE
different epochNonce on different machine with leaderlog?

### ISSUE THREAD

**Issue by monkey-jsun** [AndrewWestberg/cncli#89]
I'm upgrading my staking pool machine.  I kept everything the same on the new machine (vrf, kes, pool id, and even public IP, etc).  However, I rebuilt cncli sync db from scratch on the new machine.

When I ran leaderlog, I found the epochNonce values are different on the old and new machine.  This is quite a surprise, as I thought the new machine would be identical to the old one.  With different epochNonce values, I would think we will have different leader slots calculated somewhere somehow.

If this a real concern?  Or am I just paranoid?

**Comment by AndrewWestberg** [comment]
If you're getting different epoch nonce values, one of the databases is likely corrupt. Delete all the cncli.db* files and re-sync.

**Comment by monkey-jsun** [comment]
Can running 2 "cncli sync" at the same time cause a db corruption?  I do have such use cases in my script.

**Comment by monkey-jsun** [comment]
is there is a way to checking sync'ing process until 100% is reached without actually doing sync?  If so, then I can make a process doing this way of checking only.

**Comment by AndrewWestberg** [comment]
You cannot run multiple cncli in parallel. It does not work that way.

**Comment by monkey-jsun** [comment]
My use case is 

- I have a cncli-sync.service running in the back to sync up the db all the time
- I have foreground script to check slot leaders.

I want the foregound script to wait for background cncli-sync service until db is 100% sync'ed up.  How do I achieve this use?

**Comment by AndrewWestberg** [comment]
Well, one way is to not use the cncli-sync.service. Just don't sync the db all the time. Then, in your script that checks for leaders, run `cncli sync ... --no-service`. This will sync the db up to 100% and then exit so your script can continue and check for leaders.

**Comment by monkey-jsun** [comment]
Thanks for the advice.  I eventually used checking log method.  See code snippet below.
```
echo
echo wait for sync to reach 100% ...
while true; do
    log=$(journalctl  -n 1 --unit=cncli-sync | grep synced)
    echo 
    echo $log
    if [[ "$log" =~ .*"100.00% synced".* ]]; then
        break
    fi
    sleep 2
done
```
