### ISSUE TITLE
"EOF while parsing a value at line 1 column 0"

### ISSUE THREAD

**Issue by ianoble** [AndrewWestberg/cncli#93]
I've tried getting logs (after 290 started) on multiple servers and I get the same result every time.

`cncli leaderlog --pool-id ${NODE_HOME}/stakepoolid.txt --pool-vrf-skey ${NODE_HOME}/vrf.skey --byron-genesis ${NODE_HOME}/mainnet-byron-genesis.json --shelley-genesis ${NODE_HOME}/mainnet-shelley-genesis.json --ledger-set current`

{
  "status": "error",
  "errorMessage": "EOF while parsing a value at line 1 column 0"
}

My database is synced (cncli status... OK). My node is fully sync'd.

It worked hours before the epoch change. Is there something I need to update for Alonzo?

Anything you need from me?

**Comment by inimrod** [comment]
Up on this. Been getting the same issue. Tried with and without ledger-state file provided:

`````
cncli leaderlog \
> --pool-id <our-pool-id> \
> --pool-vrf-skey <path/to/vrf.skey> \
> --byron-genesis <path/to/mainnet-byron-genesis.json> \
> --shelley-genesis <path/to/mainnet-shelley-genesis.json> \
> --ledger-state <path/to/ledger-state.json> \
> --db <path/to/cncli.db> \
> --ledger-set current
`````

result:

```
{
  "status": "error",
  "errorMessage": "expected value at line 1 column 1"
}
```

**Comment by AndrewWestberg** [comment]
Update to using the stake-snapshot method provided in the documentation.

**Comment by ianoble** [comment]
Thanks. I should note that in the example given, it's flagged for "next" epoch, which threw me off. Once I changed to "current", the stake-snapshot worked for me.

But why did the other method break? Is it going to be fixed?

**Comment by AndrewWestberg** [comment]
The ledger state dump has breaking changes with every release which makes it difficult to parse. The stake-snapshot command will be supported in the future. I will probably remove the ledger dump support now that it broke yet again at Alonzo.

**Comment by ianoble** [comment]
Gotcha. This really seems like something IOHK should be supplying. 

The stake-snapshot method worked for getting my percentages. Need to find a way to get the full schedule, now.

**Comment by billionairepool** [comment]
If you are following the example in docs, just echo the output of the $BCSH variable. it cointains all the info in usual json format
